services:
  iot1:
    build: ./iot_device
    networks:
      macvlan_net:
        ipv4_address: ${IOT1_IP}

  iot2:
    build: ./iot_device
    networks:
      macvlan_net:
        ipv4_address: ${IOT2_IP}

  iot3:
    build: ./iot_device
    networks:
      macvlan_net:
        ipv4_address: ${IOT3_IP}

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: ${INTERFACE}
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
